import type { FastifyInstance } from 'fastify';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import config from '../../config/env.js';
import logger from '../../infra/logger/logger.js';

/**
 * Register Swagger/OpenAPI documentation
 */
export async function registerSwagger(fastify: FastifyInstance): Promise<void> {
  // Only enable in non-production environments
  if (config.NODE_ENV === 'production') {
    logger.info('Swagger UI disabled in production');
    return;
  }

  await fastify.register(swagger, {
    openapi: {
      info: {
        title: `${config.SERVICE_NAME} API`,
        description: 'API documentation generated by Fastify Swagger',
        version: config.SERVICE_VERSION,
        contact: {
          name: 'API Team',
          email: 'api@example.com',
        },
      },
      servers: [
        {
          url: `http://localhost:${config.PORT}`,
          description: 'Local development server',
        },
      ],
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
            description: 'JWT token for authentication',
          },
        },
      },
      tags: [
        { name: 'Health', description: 'Health check endpoints' },
        { name: 'Auth', description: 'Authentication endpoints' },
        // Add more tags as needed
      ],
    },
  });

  await fastify.register(swaggerUi, {
    routePrefix: '/docs',
    uiConfig: {
      docExpansion: 'list',
      deepLinking: true,
      persistAuthorization: true,
    },
    staticCSP: true,
  });

  logger.info({ url: `/docs` }, '📚 Swagger UI registered');
}

/**
 * Common schema definitions for Swagger
 */
export const swaggerSchemas = {
  // Error response schema
  errorResponse: {
    type: 'object',
    properties: {
      statusCode: { type: 'number' },
      error: { type: 'string' },
      message: { type: 'string' },
    },
  },

  // Pagination query params
  paginationQuery: {
    type: 'object',
    properties: {
      page: { type: 'number', default: 1, minimum: 1 },
      limit: { type: 'number', default: 20, minimum: 1, maximum: 100 },
    },
  },

  // Health check response
  healthResponse: {
    type: 'object',
    properties: {
      status: { type: 'string', enum: ['ok', 'degraded', 'dead'] },
      service: { type: 'string' },
      version: { type: 'string' },
      timestamp: { type: 'string', format: 'date-time' },
      uptime: { type: 'number' },
    },
  },
};
